spring:
  application:
    name: spring-ai-rag-jt
#Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      # configure a chat model and a temperature of 0.7
      chat:
        options:
            model: gpt-5.4-nano
            #temperature: 0.7
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json # will store under C:\tmp\vectorstore.json on Windows
    documentsToLoad:
      - classpath:/movies500.csv

# enable debug logging for the config and Spring AI chat client advisor
logging:
  level:
    guru.springframework.springairag.config: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG