spring:
  application:
    name: spring-ai-rag

  # Enable color output on console
  output:
    ansi:
      enabled: always


  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

# enable Advisor logging
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

# application.properties
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500.csv