spring:
  application:
    name: spring-ai-rag

  # Enable color output on console
  output:
    ansi:
      enabled: always


  #Pass API key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          # possible values: text-embedding-3-small, text-embedding-3-large
          # default: text-embedding-ada-002
          model: text-embedding-3-small
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - classpath:/movies500.csv